-- -- golang_dbという名前のデータベースを作成
-- CREATE DATABASE IF NOT EXISTS golang_db;
-- -- golang_dbをアクティブ
-- use golang_db;
-- -- usersテーブルを作成。名前とパスワード
-- CREATE TABLE users (
--     id INT(11) AUTO_INCREMENT NOT NULL,
--     uuid VARCHAR(64),
--     name VARCHAR(64) NOT NULL,
--     email VARCHAR(64),
--     password CHAR(30) NOT NULL,
--     create_at DATETIME

-- );
-- -- usersテーブルに２つレコードを追加
-- INSERT INTO users (name,email,password) VALUES ("gophar", "go@com","5555");
-- INSERT INTO users (name,email,password) VALUES ("octcat", "daf@go","0000");